# Generated by Django 4.2.6 on 2023-10-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(choices=[('HR', 1), ('IT', 2), ('SALES', 3), ('MARKETING', 4), ('FINANCE', 5), ('OPERATIONS', 6), ('CUSTOMER_SERVICE', 7), ('ADMINISTRATION', 8), ('RESEARCH_AND_DEVELOPMENT', 9), ('PROCUREMENT', 10)], max_length=100),
        ),
    ]
