# Generated by Django 4.2.6 on 2023-10-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('SALES', 'Sales'), ('MARKETING', 'Marketing'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations'), ('CUSTOMER_SERVICE', 'Customer Service'), ('ADMINISTRATION', 'Administration'), ('RESEARCH_AND_DEVELOPMENT', 'R&D'), ('PROCUREMENT', 'Procurement')], max_length=100),
        ),
    ]
